package ma.munisys.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
//import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import ma.munisys.dao.AuthRepository;
import ma.munisys.dao.ProfileRepository;
import ma.munisys.dao.UserRepository;

import ma.munisys.entities.AppProfile;
import ma.munisys.entities.AppUser;
import ma.munisys.entities.Authorisation;

@Service
@Transactional // spring pas javax
public class AccountServiceImp implements AccountService {
	
	
	@Autowired
	private UserRepository userRepository;
	
	@Autowired
	private ProfileRepository profileRepository;
	
	@Autowired
	private AuthRepository authRepository;

	/*
	@Override
	public AppUser saveUser(AppUser appUser) {
		String hashPW = bCryptPasswordEncoder.encode(appUser.getPassword());
		appUser.setPassword(hashPW);
		return userRepository.save(appUser);
	}*/

	

	@Override
	public AppUser findUserByUsername(String username) {
		// TODO Auto-generated method stub
		return userRepository.findByUsername(username);
	}

	@Override
	public AppUser saveUser(AppUser appUser) {
		// TODO Auto-generated method stub
		return userRepository.save(appUser);
	}

	@Override
	public AppProfile saveProfile(AppProfile profile) {
		// TODO Autogenerated method stub
		return profileRepository.save(profile);
	}

	@Override
	public void addProfileToUser(String username, String profileName) {
		AppProfile profile = profileRepository.findByPrflName(profileName);
		AppUser user = userRepository.findByUsername(username);
		profile.getAppUsers().add(user);
	}

	@Override
	public void addAuthorisationToProfile(String authorisation, String profileName) {
		// TODO Auto-generated method stub
		AppProfile profile = profileRepository.findByPrflName(profileName);
		Authorisation authorisation2 = authRepository.findByAuthName(authorisation);
		profile.getAuthorities().add(authorisation2);
	}

	@Override
	public Authorisation saveAuthorisation(String authorisationName) {
		// TODO Auto-generated method stub
		//return authRepository.save(new Authorisation(null,authorisationName));
		return null;
	}

	@Override
	public void addAuthorisationToUser(String authorisation, String username) {
		AppUser user = userRepository.findByUsername(username);
		Authorisation authorisation2 = authRepository.findByAuthName(authorisation);
		user.getAuthorities().add(authorisation2);
		
	}
	
	@Override
	public List<AppProfile> findProfilesByUsers(String username) {
		// TODO Auto-generated method stub
		return profileRepository.findProfilesByUsers(username);
	}

	@Override
	public List<Authorisation> findAuthorityByPrflName(String profileName) {
		// TODO Auto-generated method stub
		return profileRepository.findAuthorityByPrflName(profileName);
	}

	@Override
	public List<Authorisation> findUserAuthority(String username) {
		// TODO Auto-generated method stub
		return userRepository.findUserAuthority(username);
	}
	
	public ma.munisys.entities.Service getService(String username) {
		return userRepository.findByUsername(username).getService();
	}

	@Override
	public String getSigle(String username) {
		// TODO Auto-generated method stub
		return userRepository.findSigleUser(username);
	}

	@Override
	public String getFullName(String username) {
		// TODO Auto-generated method stub
		return userRepository.findNameByUser(username);
	}

	
	

}
